! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : aqchem_Global.F90
! Time                 : Tue Jun 23 16:56:52 2015
! Working directory    : /home/kfahey/kpp-2.2.3/ASSUMPTION_TEST/CLEAN_INIT/TESTS/CMAQ_BASE_022414/3D/FINAL_120114/AERO5
! Equation file        : aqchem.kpp
! Output root filename : aqchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE aqchem_Global

  USE aqchem_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
!     EQUIVALENCE( C(1),VAR(1) )
!     EQUIVALENCE( C(83),FIX(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR

! INLINED global variable declarations

!
REAL( kind=dp ), PARAMETER :: INV_T300 = 1.0D0 / 300.0D0 ! reciprocal 300K
REAL( kind=dp )            :: CAIR          ! air number density (wet) [molec/cm^3]
REAL( kind=dp )            :: INV_TEMP      ! reciprocal of air temperature, K-1
REAL( kind=dp )            :: PRESS         ! pressure [Atm] 
REAL( kind=dp )            :: INV_RFACTOR   ! Convertor: ppm/min to molec/(cm^3*sec)
REAL( kind=dp )            :: RFACTOR_SQU   ! Convertor cm^6/(molec^2*sec) to 1/(ppm^2*min)
REAL( kind=dp )            :: RFACTOR       ! Convertor cm^3/(molec*sec) to 1/(ppm*min)
REAL( kind=dp )            :: COEFF_FALLOFF ! Factor in pressure limiting rate constants, [molec/cm^3] 
!REAL                :: H2O                ! Cell H2O mixing ratio (ppmV)

REAL( kind=dp ),      PARAMETER :: PHI = 6.0221413D17
REAL( kind=dp ),      PARAMETER :: DAQ = 1.d-9 !aqueous phase diffusion coefficient (m2/s)


! switch for Time Independent Rate Constants
      INTEGER Autonomous
      REAL( kind=dp ) STEPSTART
! TEMP_KPP
      REAL( kind=dp ) TEMP_KPP
! LWCP_KPP
      REAL( kind=dp ) LWC_KPP
      REAL( kind=dp ) LWCFRAC
! ALFA3_KPP
      REAL( kind=dp ) ALFA3_KPP
      REAL( kind=dp ) ALFA0_KPP
      REAL( kind=dp ) PHI2, INVPHI2  
      REAL( kind=dp ) STION  ! Ionic strength
      REAL( kind=dp ) GM1LOG, GM2LOG, GM1, GM2
      
! WETFAC_KPP
      REAL( kind=dp ) WETFAC_KPP  
!      REAL( kind=dp ) FE_III
!      REAL( kind=dp ) MN_II
!      REAL( kind=dp ) FE_SOL
!      REAL( kind=dp ) MN_SOL 
      REAL( kind=dp ) DELINVT
            
! Droplet Diameter (m)
      REAL( kind=dp ) DDIAM     
         
! MGLY H Law Constant -- dependent on gas phase mechanism
      REAL( kind=dp ) MGLYH 
      
      INTEGER JDATEKPP
      INTEGER JTIMEKPP   


! INLINED global variable declarations


END MODULE aqchem_Global

