! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : aqchem_HessianSP.f90
! Time                 : Thu Jul 30 16:04:52 2015
! Working directory    : /home/slz/buf/dev/cmaq-adj/ad/aqchem-kpp/src-aero5-adj
! Equation file        : aqchem.kpp
! Output root filename : aqchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE aqchem_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(92) :: IHESS_I = (/ &
      60, 61, 62, 63, 64, 64, 65, 66, 67, 68, 69, 70, &
      71, 72, 72, 73, 73, 74, 74, 74, 75, 75, 75, 76, &
      76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, &
      76, 76, 76, 76, 76, 77, 77, 77, 78, 78, 78, 78, &
      78, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, &
      79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, &
      80, 80, 80, 81, 81, 81, 81, 81, 81, 81, 81, 81, &
      81, 81, 81, 82, 82, 82, 82, 82 /)

  INTEGER, PARAMETER, DIMENSION(92) :: IHESS_J = (/ &
      61, 61, 63, 63, 63, 64, 66, 66, 73, 69, 69, 70, &
      72, 70, 72, 73, 76, 74, 74, 79, 75, 75, 79, 12, &
      12, 12, 12, 13, 13, 13, 74, 74, 75, 75, 76, 77, &
      77, 78, 79, 80, 80, 77, 77, 79, 12, 12, 13, 78, &
      78, 12, 12, 12, 13, 13, 61, 64, 66, 69, 70, 72, &
      73, 74, 74, 75, 75, 76, 77, 77, 78, 79, 80, 80, &
      78, 80, 80, 12, 12, 13, 74, 74, 75, 75, 77, 77, &
      78, 79, 80, 12, 12, 13, 79, 80 /)

  INTEGER, PARAMETER, DIMENSION(92) :: IHESS_K = (/ &
      79, 79, 64, 64, 64, 79, 79, 79, 79, 79, 79, 79, &
      79, 79, 79, 79, 79, 79, 81, 81, 79, 81, 81, 13, &
      78, 81, 82, 78, 81, 82, 79, 81, 79, 81, 79, 79, &
      81, 80, 81, 81, 82, 79, 81, 81, 13, 78, 78, 79, &
      80, 13, 81, 82, 81, 82, 79, 79, 79, 79, 79, 79, &
      79, 79, 81, 79, 81, 79, 79, 81, 79, 81, 81, 82, &
      80, 81, 82, 13, 81, 81, 79, 81, 79, 81, 79, 81, &
      79, 81, 81, 13, 82, 82, 81, 82 /)


END MODULE aqchem_HessianSP

