! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Hessian File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : aqchem_Hessian.f90
! Time                 : Thu Jul 30 16:04:52 2015
! Working directory    : /home/slz/buf/dev/cmaq-adj/ad/aqchem-kpp/src-aero5-adj
! Equation file        : aqchem.kpp
! Output root filename : aqchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE aqchem_Hessian

  USE aqchem_Parameters
  USE aqchem_HessianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Hessian - function for Hessian (Jac derivative w.r.t. variables)
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Hessian ( V, F, RCT, HESS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! HESS - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
  REAL(kind=dp) :: HESS(NHESS)

! --------------------------------------------------------
! Note: HESS is represented in coordinate sparse format:
!       HESS(m) = d^2 f_i / dv_j dv_k = d Jac_{i,j} / dv_k
!       where i = IHESS_I(m), j = IHESS_J(m), k = IHESS_K(m).
! --------------------------------------------------------
! Note: d^2 f_i / dv_j dv_k = d^2 f_i / dv_k dv_j,
!       therefore only the terms d^2 f_i / dv_j dv_k
!       with j <= k are computed and stored in HESS.
! --------------------------------------------------------

! Local variables
! D2A - Second derivatives of equation rates
  REAL(kind=dp) :: D2A(39)

! Computation of the second derivatives of equation rates
! D2A(1) = d^2 A(44) / dV(79)dV(81)
  D2A(1) = RCT(44)
! D2A(2) = d^2 A(45) / dV(78)dV(79)
  D2A(2) = RCT(45)
! D2A(3) = d^2 A(46) / dV(61)dV(79)
  D2A(3) = RCT(46)
! D2A(4) = d^2 A(47) / dV(72)dV(79)
  D2A(4) = RCT(47)
! D2A(5) = d^2 A(48) / dV(70)dV(79)
  D2A(5) = RCT(48)
! D2A(6) = d^2 A(49) / dV(63)dV(64)
  D2A(6) = RCT(49)
! D2A(7) = d^2 A(50) / dV(66)dV(79)
  D2A(7) = RCT(50)
! D2A(8) = d^2 A(51) / dV(69)dV(79)
  D2A(8) = RCT(51)
! D2A(9) = d^2 A(52) / dV(64)dV(79)
  D2A(9) = RCT(52)
! D2A(10) = d^2 A(53) / dV(73)dV(79)
  D2A(10) = RCT(53)
! D2A(11) = d^2 A(54) / dV(76)dV(79)
  D2A(11) = RCT(54)
! D2A(12) = d^2 A(57) / dV(74)dV(79)
  D2A(12) = RCT(57)*V(81)
! D2A(13) = d^2 A(57) / dV(74)dV(81)
  D2A(13) = RCT(57)*V(79)
! D2A(14) = d^2 A(57) / dV(79)dV(81)
  D2A(14) = RCT(57)*V(74)
! D2A(15) = d^2 A(58) / dV(80)dV(82)
  D2A(15) = RCT(58)
! D2A(16) = d^2 A(59) / dV(80)dV(81)
  D2A(16) = RCT(59)
! D2A(17) = d^2 A(60) / dV(78)dV(80)
  D2A(17) = RCT(60)
! D2A(18) = d^2 A(61) / dV(13)dV(82)
  D2A(18) = RCT(61)
! D2A(19) = d^2 A(62) / dV(13)dV(81)
  D2A(19) = RCT(62)
! D2A(20) = d^2 A(63) / dV(13)dV(78)
  D2A(20) = RCT(63)
! D2A(21) = d^2 A(64) / dV(12)dV(82)
  D2A(21) = RCT(64)
! D2A(22) = d^2 A(65) / dV(12)dV(81)
  D2A(22) = RCT(65)
! D2A(23) = d^2 A(66) / dV(12)dV(78)
  D2A(23) = RCT(66)
! D2A(24) = d^2 A(67) / dV(12)dV(13)
  D2A(24) = RCT(67)*V(82)
! D2A(25) = d^2 A(67) / dV(12)dV(82)
  D2A(25) = RCT(67)*V(13)
! D2A(26) = d^2 A(67) / dV(13)dV(82)
  D2A(26) = RCT(67)*V(12)
! D2A(27) = d^2 A(68) / dV(12)dV(13)
  D2A(27) = RCT(68)*V(81)
! D2A(28) = d^2 A(68) / dV(12)dV(81)
  D2A(28) = RCT(68)*V(13)
! D2A(29) = d^2 A(68) / dV(13)dV(81)
  D2A(29) = RCT(68)*V(12)
! D2A(30) = d^2 A(69) / dV(12)dV(13)
  D2A(30) = RCT(69)*V(78)
! D2A(31) = d^2 A(69) / dV(12)dV(78)
  D2A(31) = RCT(69)*V(13)
! D2A(32) = d^2 A(69) / dV(13)dV(78)
  D2A(32) = RCT(69)*V(12)
! D2A(33) = d^2 A(70) / dV(77)dV(79)
  D2A(33) = RCT(70)*V(81)
! D2A(34) = d^2 A(70) / dV(77)dV(81)
  D2A(34) = RCT(70)*V(79)
! D2A(35) = d^2 A(70) / dV(79)dV(81)
  D2A(35) = RCT(70)*V(77)
! D2A(36) = d^2 A(71) / dV(75)dV(79)
  D2A(36) = RCT(71)*V(81)
! D2A(37) = d^2 A(71) / dV(75)dV(81)
  D2A(37) = RCT(71)*V(79)
! D2A(38) = d^2 A(71) / dV(79)dV(81)
  D2A(38) = RCT(71)*V(75)
! D2A(39) = d^2 A(72) / dV(75)dV(81)
  D2A(39) = RCT(72)

! Computation of the Jacobian derivative
! HESS(1) = d^2 Vdot(60)/{dV(61)dV(79)} = d^2 Vdot(60)/{dV(79)dV(61)}
  HESS(1) = D2A(3)
! HESS(2) = d^2 Vdot(61)/{dV(61)dV(79)} = d^2 Vdot(61)/{dV(79)dV(61)}
  HESS(2) = -D2A(3)
! HESS(3) = d^2 Vdot(62)/{dV(63)dV(64)} = d^2 Vdot(62)/{dV(64)dV(63)}
  HESS(3) = D2A(6)
! HESS(4) = d^2 Vdot(63)/{dV(63)dV(64)} = d^2 Vdot(63)/{dV(64)dV(63)}
  HESS(4) = -D2A(6)
! HESS(5) = d^2 Vdot(64)/{dV(63)dV(64)} = d^2 Vdot(64)/{dV(64)dV(63)}
  HESS(5) = -D2A(6)
! HESS(6) = d^2 Vdot(64)/{dV(64)dV(79)} = d^2 Vdot(64)/{dV(79)dV(64)}
  HESS(6) = -D2A(9)
! HESS(7) = d^2 Vdot(65)/{dV(66)dV(79)} = d^2 Vdot(65)/{dV(79)dV(66)}
  HESS(7) = D2A(7)
! HESS(8) = d^2 Vdot(66)/{dV(66)dV(79)} = d^2 Vdot(66)/{dV(79)dV(66)}
  HESS(8) = -D2A(7)
! HESS(9) = d^2 Vdot(67)/{dV(73)dV(79)} = d^2 Vdot(67)/{dV(79)dV(73)}
  HESS(9) = D2A(10)
! HESS(10) = d^2 Vdot(68)/{dV(69)dV(79)} = d^2 Vdot(68)/{dV(79)dV(69)}
  HESS(10) = D2A(8)
! HESS(11) = d^2 Vdot(69)/{dV(69)dV(79)} = d^2 Vdot(69)/{dV(79)dV(69)}
  HESS(11) = -D2A(8)
! HESS(12) = d^2 Vdot(70)/{dV(70)dV(79)} = d^2 Vdot(70)/{dV(79)dV(70)}
  HESS(12) = -D2A(5)
! HESS(13) = d^2 Vdot(71)/{dV(72)dV(79)} = d^2 Vdot(71)/{dV(79)dV(72)}
  HESS(13) = D2A(4)
! HESS(14) = d^2 Vdot(72)/{dV(70)dV(79)} = d^2 Vdot(72)/{dV(79)dV(70)}
  HESS(14) = D2A(5)
! HESS(15) = d^2 Vdot(72)/{dV(72)dV(79)} = d^2 Vdot(72)/{dV(79)dV(72)}
  HESS(15) = -D2A(4)
! HESS(16) = d^2 Vdot(73)/{dV(73)dV(79)} = d^2 Vdot(73)/{dV(79)dV(73)}
  HESS(16) = -D2A(10)
! HESS(17) = d^2 Vdot(73)/{dV(76)dV(79)} = d^2 Vdot(73)/{dV(79)dV(76)}
  HESS(17) = D2A(11)
! HESS(18) = d^2 Vdot(74)/{dV(74)dV(79)} = d^2 Vdot(74)/{dV(79)dV(74)}
  HESS(18) = -D2A(12)
! HESS(19) = d^2 Vdot(74)/{dV(74)dV(81)} = d^2 Vdot(74)/{dV(81)dV(74)}
  HESS(19) = -D2A(13)
! HESS(20) = d^2 Vdot(74)/{dV(79)dV(81)} = d^2 Vdot(74)/{dV(81)dV(79)}
  HESS(20) = -D2A(14)
! HESS(21) = d^2 Vdot(75)/{dV(75)dV(79)} = d^2 Vdot(75)/{dV(79)dV(75)}
  HESS(21) = -D2A(36)
! HESS(22) = d^2 Vdot(75)/{dV(75)dV(81)} = d^2 Vdot(75)/{dV(81)dV(75)}
  HESS(22) = -D2A(37)-D2A(39)
! HESS(23) = d^2 Vdot(75)/{dV(79)dV(81)} = d^2 Vdot(75)/{dV(81)dV(79)}
  HESS(23) = -D2A(38)
! HESS(24) = d^2 Vdot(76)/{dV(12)dV(13)} = d^2 Vdot(76)/{dV(13)dV(12)}
  HESS(24) = D2A(24)+D2A(27)+D2A(30)
! HESS(25) = d^2 Vdot(76)/{dV(12)dV(78)} = d^2 Vdot(76)/{dV(78)dV(12)}
  HESS(25) = D2A(23)+D2A(31)
! HESS(26) = d^2 Vdot(76)/{dV(12)dV(81)} = d^2 Vdot(76)/{dV(81)dV(12)}
  HESS(26) = D2A(22)+D2A(28)
! HESS(27) = d^2 Vdot(76)/{dV(12)dV(82)} = d^2 Vdot(76)/{dV(82)dV(12)}
  HESS(27) = D2A(21)+D2A(25)
! HESS(28) = d^2 Vdot(76)/{dV(13)dV(78)} = d^2 Vdot(76)/{dV(78)dV(13)}
  HESS(28) = D2A(20)+D2A(32)
! HESS(29) = d^2 Vdot(76)/{dV(13)dV(81)} = d^2 Vdot(76)/{dV(81)dV(13)}
  HESS(29) = D2A(19)+D2A(29)
! HESS(30) = d^2 Vdot(76)/{dV(13)dV(82)} = d^2 Vdot(76)/{dV(82)dV(13)}
  HESS(30) = D2A(18)+D2A(26)
! HESS(31) = d^2 Vdot(76)/{dV(74)dV(79)} = d^2 Vdot(76)/{dV(79)dV(74)}
  HESS(31) = D2A(12)
! HESS(32) = d^2 Vdot(76)/{dV(74)dV(81)} = d^2 Vdot(76)/{dV(81)dV(74)}
  HESS(32) = D2A(13)
! HESS(33) = d^2 Vdot(76)/{dV(75)dV(79)} = d^2 Vdot(76)/{dV(79)dV(75)}
  HESS(33) = D2A(36)
! HESS(34) = d^2 Vdot(76)/{dV(75)dV(81)} = d^2 Vdot(76)/{dV(81)dV(75)}
  HESS(34) = D2A(37)+D2A(39)
! HESS(35) = d^2 Vdot(76)/{dV(76)dV(79)} = d^2 Vdot(76)/{dV(79)dV(76)}
  HESS(35) = -D2A(11)
! HESS(36) = d^2 Vdot(76)/{dV(77)dV(79)} = d^2 Vdot(76)/{dV(79)dV(77)}
  HESS(36) = D2A(33)
! HESS(37) = d^2 Vdot(76)/{dV(77)dV(81)} = d^2 Vdot(76)/{dV(81)dV(77)}
  HESS(37) = D2A(34)
! HESS(38) = d^2 Vdot(76)/{dV(78)dV(80)} = d^2 Vdot(76)/{dV(80)dV(78)}
  HESS(38) = D2A(17)
! HESS(39) = d^2 Vdot(76)/{dV(79)dV(81)} = d^2 Vdot(76)/{dV(81)dV(79)}
  HESS(39) = D2A(14)+D2A(35)+D2A(38)
! HESS(40) = d^2 Vdot(76)/{dV(80)dV(81)} = d^2 Vdot(76)/{dV(81)dV(80)}
  HESS(40) = D2A(16)
! HESS(41) = d^2 Vdot(76)/{dV(80)dV(82)} = d^2 Vdot(76)/{dV(82)dV(80)}
  HESS(41) = D2A(15)
! HESS(42) = d^2 Vdot(77)/{dV(77)dV(79)} = d^2 Vdot(77)/{dV(79)dV(77)}
  HESS(42) = -D2A(33)
! HESS(43) = d^2 Vdot(77)/{dV(77)dV(81)} = d^2 Vdot(77)/{dV(81)dV(77)}
  HESS(43) = -D2A(34)
! HESS(44) = d^2 Vdot(77)/{dV(79)dV(81)} = d^2 Vdot(77)/{dV(81)dV(79)}
  HESS(44) = -D2A(35)
! HESS(45) = d^2 Vdot(78)/{dV(12)dV(13)} = d^2 Vdot(78)/{dV(13)dV(12)}
  HESS(45) = -D2A(30)
! HESS(46) = d^2 Vdot(78)/{dV(12)dV(78)} = d^2 Vdot(78)/{dV(78)dV(12)}
  HESS(46) = -D2A(23)-D2A(31)
! HESS(47) = d^2 Vdot(78)/{dV(13)dV(78)} = d^2 Vdot(78)/{dV(78)dV(13)}
  HESS(47) = -D2A(20)-D2A(32)
! HESS(48) = d^2 Vdot(78)/{dV(78)dV(79)} = d^2 Vdot(78)/{dV(79)dV(78)}
  HESS(48) = -D2A(2)
! HESS(49) = d^2 Vdot(78)/{dV(78)dV(80)} = d^2 Vdot(78)/{dV(80)dV(78)}
  HESS(49) = -D2A(17)
! HESS(50) = d^2 Vdot(79)/{dV(12)dV(13)} = d^2 Vdot(79)/{dV(13)dV(12)}
  HESS(50) = 2*D2A(24)+D2A(27)
! HESS(51) = d^2 Vdot(79)/{dV(12)dV(81)} = d^2 Vdot(79)/{dV(81)dV(12)}
  HESS(51) = D2A(22)+D2A(28)
! HESS(52) = d^2 Vdot(79)/{dV(12)dV(82)} = d^2 Vdot(79)/{dV(82)dV(12)}
  HESS(52) = 2*D2A(21)+2*D2A(25)
! HESS(53) = d^2 Vdot(79)/{dV(13)dV(81)} = d^2 Vdot(79)/{dV(81)dV(13)}
  HESS(53) = D2A(19)+D2A(29)
! HESS(54) = d^2 Vdot(79)/{dV(13)dV(82)} = d^2 Vdot(79)/{dV(82)dV(13)}
  HESS(54) = 2*D2A(18)+2*D2A(26)
! HESS(55) = d^2 Vdot(79)/{dV(61)dV(79)} = d^2 Vdot(79)/{dV(79)dV(61)}
  HESS(55) = -D2A(3)
! HESS(56) = d^2 Vdot(79)/{dV(64)dV(79)} = d^2 Vdot(79)/{dV(79)dV(64)}
  HESS(56) = -D2A(9)
! HESS(57) = d^2 Vdot(79)/{dV(66)dV(79)} = d^2 Vdot(79)/{dV(79)dV(66)}
  HESS(57) = -D2A(7)
! HESS(58) = d^2 Vdot(79)/{dV(69)dV(79)} = d^2 Vdot(79)/{dV(79)dV(69)}
  HESS(58) = -D2A(8)
! HESS(59) = d^2 Vdot(79)/{dV(70)dV(79)} = d^2 Vdot(79)/{dV(79)dV(70)}
  HESS(59) = -D2A(5)
! HESS(60) = d^2 Vdot(79)/{dV(72)dV(79)} = d^2 Vdot(79)/{dV(79)dV(72)}
  HESS(60) = -D2A(4)
! HESS(61) = d^2 Vdot(79)/{dV(73)dV(79)} = d^2 Vdot(79)/{dV(79)dV(73)}
  HESS(61) = -D2A(10)
! HESS(62) = d^2 Vdot(79)/{dV(74)dV(79)} = d^2 Vdot(79)/{dV(79)dV(74)}
  HESS(62) = D2A(12)
! HESS(63) = d^2 Vdot(79)/{dV(74)dV(81)} = d^2 Vdot(79)/{dV(81)dV(74)}
  HESS(63) = D2A(13)
! HESS(64) = d^2 Vdot(79)/{dV(75)dV(79)} = d^2 Vdot(79)/{dV(79)dV(75)}
  HESS(64) = D2A(36)
! HESS(65) = d^2 Vdot(79)/{dV(75)dV(81)} = d^2 Vdot(79)/{dV(81)dV(75)}
  HESS(65) = D2A(37)+D2A(39)
! HESS(66) = d^2 Vdot(79)/{dV(76)dV(79)} = d^2 Vdot(79)/{dV(79)dV(76)}
  HESS(66) = -D2A(11)
! HESS(67) = d^2 Vdot(79)/{dV(77)dV(79)} = d^2 Vdot(79)/{dV(79)dV(77)}
  HESS(67) = D2A(33)
! HESS(68) = d^2 Vdot(79)/{dV(77)dV(81)} = d^2 Vdot(79)/{dV(81)dV(77)}
  HESS(68) = D2A(34)
! HESS(69) = d^2 Vdot(79)/{dV(78)dV(79)} = d^2 Vdot(79)/{dV(79)dV(78)}
  HESS(69) = -D2A(2)
! HESS(70) = d^2 Vdot(79)/{dV(79)dV(81)} = d^2 Vdot(79)/{dV(81)dV(79)}
  HESS(70) = -D2A(1)+D2A(14)+D2A(35)+D2A(38)
! HESS(71) = d^2 Vdot(79)/{dV(80)dV(81)} = d^2 Vdot(79)/{dV(81)dV(80)}
  HESS(71) = D2A(16)
! HESS(72) = d^2 Vdot(79)/{dV(80)dV(82)} = d^2 Vdot(79)/{dV(82)dV(80)}
  HESS(72) = 2*D2A(15)
! HESS(73) = d^2 Vdot(80)/{dV(78)dV(80)} = d^2 Vdot(80)/{dV(80)dV(78)}
  HESS(73) = -D2A(17)
! HESS(74) = d^2 Vdot(80)/{dV(80)dV(81)} = d^2 Vdot(80)/{dV(81)dV(80)}
  HESS(74) = -D2A(16)
! HESS(75) = d^2 Vdot(80)/{dV(80)dV(82)} = d^2 Vdot(80)/{dV(82)dV(80)}
  HESS(75) = -D2A(15)
! HESS(76) = d^2 Vdot(81)/{dV(12)dV(13)} = d^2 Vdot(81)/{dV(13)dV(12)}
  HESS(76) = -D2A(27)
! HESS(77) = d^2 Vdot(81)/{dV(12)dV(81)} = d^2 Vdot(81)/{dV(81)dV(12)}
  HESS(77) = -D2A(22)-D2A(28)
! HESS(78) = d^2 Vdot(81)/{dV(13)dV(81)} = d^2 Vdot(81)/{dV(81)dV(13)}
  HESS(78) = -D2A(19)-D2A(29)
! HESS(79) = d^2 Vdot(81)/{dV(74)dV(79)} = d^2 Vdot(81)/{dV(79)dV(74)}
  HESS(79) = -D2A(12)
! HESS(80) = d^2 Vdot(81)/{dV(74)dV(81)} = d^2 Vdot(81)/{dV(81)dV(74)}
  HESS(80) = -D2A(13)
! HESS(81) = d^2 Vdot(81)/{dV(75)dV(79)} = d^2 Vdot(81)/{dV(79)dV(75)}
  HESS(81) = -D2A(36)
! HESS(82) = d^2 Vdot(81)/{dV(75)dV(81)} = d^2 Vdot(81)/{dV(81)dV(75)}
  HESS(82) = -D2A(37)-D2A(39)
! HESS(83) = d^2 Vdot(81)/{dV(77)dV(79)} = d^2 Vdot(81)/{dV(79)dV(77)}
  HESS(83) = -D2A(33)
! HESS(84) = d^2 Vdot(81)/{dV(77)dV(81)} = d^2 Vdot(81)/{dV(81)dV(77)}
  HESS(84) = -D2A(34)
! HESS(85) = d^2 Vdot(81)/{dV(78)dV(79)} = d^2 Vdot(81)/{dV(79)dV(78)}
  HESS(85) = D2A(2)
! HESS(86) = d^2 Vdot(81)/{dV(79)dV(81)} = d^2 Vdot(81)/{dV(81)dV(79)}
  HESS(86) = -D2A(1)-D2A(14)-D2A(35)-D2A(38)
! HESS(87) = d^2 Vdot(81)/{dV(80)dV(81)} = d^2 Vdot(81)/{dV(81)dV(80)}
  HESS(87) = -D2A(16)
! HESS(88) = d^2 Vdot(82)/{dV(12)dV(13)} = d^2 Vdot(82)/{dV(13)dV(12)}
  HESS(88) = -D2A(24)
! HESS(89) = d^2 Vdot(82)/{dV(12)dV(82)} = d^2 Vdot(82)/{dV(82)dV(12)}
  HESS(89) = -D2A(21)-D2A(25)
! HESS(90) = d^2 Vdot(82)/{dV(13)dV(82)} = d^2 Vdot(82)/{dV(82)dV(13)}
  HESS(90) = -D2A(18)-D2A(26)
! HESS(91) = d^2 Vdot(82)/{dV(79)dV(81)} = d^2 Vdot(82)/{dV(81)dV(79)}
  HESS(91) = D2A(1)
! HESS(92) = d^2 Vdot(82)/{dV(80)dV(82)} = d^2 Vdot(82)/{dV(82)dV(80)}
  HESS(92) = -D2A(15)
      
END SUBROUTINE Hessian

! End of Hessian function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! HessTR_Vec - Hessian transposed times user vectors
!   Arguments :
!      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
!      U1        - User vector
!      U2        - User vector
!      HTU       - Transposed Hessian times user vectors: (Hess x U2)^T * U1 = [d (Jac^T*U1)/d Var] * U2
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE HessTR_Vec ( HESS, U1, U2, HTU )

! HESS - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
  REAL(kind=dp) :: HESS(NHESS)
! U1 - User vector
  REAL(kind=dp) :: U1(NVAR)
! U2 - User vector
  REAL(kind=dp) :: U2(NVAR)
! HTU - Transposed Hessian times user vectors: (Hess x U2)^T * U1 = [d (Jac^T*U1)/d Var] * U2
  REAL(kind=dp) :: HTU(NVAR)

! Compute the vector HTU =(Hess x U2)^T * U1 = d (Jac^T*U1)/d Var * U2
  HTU(1) = 0
  HTU(2) = 0
  HTU(3) = 0
  HTU(4) = 0
  HTU(5) = 0
  HTU(6) = 0
  HTU(7) = 0
  HTU(8) = 0
  HTU(9) = 0
  HTU(10) = 0
  HTU(11) = 0
  HTU(12) = HESS(24)*(U1(76)*U2(13))+HESS(25)*(U1(76)*U2(78))+HESS(26)*(U1(76)*U2(81))+HESS(27)*(U1(76)*U2(82))+HESS(45)&
              &*(U1(78)*U2(13))+HESS(46)*(U1(78)*U2(78))+HESS(50)*(U1(79)*U2(13))+HESS(51)*(U1(79)*U2(81))+HESS(52)*(U1(79)&
              &*U2(82))+HESS(76)*(U1(81)*U2(13))+HESS(77)*(U1(81)*U2(81))+HESS(88)*(U1(82)*U2(13))+HESS(89)*(U1(82)*U2(82))
  HTU(13) = HESS(24)*(U1(76)*U2(12))+HESS(28)*(U1(76)*U2(78))+HESS(29)*(U1(76)*U2(81))+HESS(30)*(U1(76)*U2(82))+HESS(45)&
              &*(U1(78)*U2(12))+HESS(47)*(U1(78)*U2(78))+HESS(50)*(U1(79)*U2(12))+HESS(53)*(U1(79)*U2(81))+HESS(54)*(U1(79)&
              &*U2(82))+HESS(76)*(U1(81)*U2(12))+HESS(78)*(U1(81)*U2(81))+HESS(88)*(U1(82)*U2(12))+HESS(90)*(U1(82)*U2(82))
  HTU(14) = 0
  HTU(15) = 0
  HTU(16) = 0
  HTU(17) = 0
  HTU(18) = 0
  HTU(19) = 0
  HTU(20) = 0
  HTU(21) = 0
  HTU(22) = 0
  HTU(23) = 0
  HTU(24) = 0
  HTU(25) = 0
  HTU(26) = 0
  HTU(27) = 0
  HTU(28) = 0
  HTU(29) = 0
  HTU(30) = 0
  HTU(31) = 0
  HTU(32) = 0
  HTU(33) = 0
  HTU(34) = 0
  HTU(35) = 0
  HTU(36) = 0
  HTU(37) = 0
  HTU(38) = 0
  HTU(39) = 0
  HTU(40) = 0
  HTU(41) = 0
  HTU(42) = 0
  HTU(43) = 0
  HTU(44) = 0
  HTU(45) = 0
  HTU(46) = 0
  HTU(47) = 0
  HTU(48) = 0
  HTU(49) = 0
  HTU(50) = 0
  HTU(51) = 0
  HTU(52) = 0
  HTU(53) = 0
  HTU(54) = 0
  HTU(55) = 0
  HTU(56) = 0
  HTU(57) = 0
  HTU(58) = 0
  HTU(59) = 0
  HTU(60) = 0
  HTU(61) = HESS(1)*(U1(60)*U2(79))+HESS(2)*(U1(61)*U2(79))+HESS(55)*(U1(79)*U2(79))
  HTU(62) = 0
  HTU(63) = HESS(3)*(U1(62)*U2(64))+HESS(4)*(U1(63)*U2(64))+HESS(5)*(U1(64)*U2(64))
  HTU(64) = HESS(3)*(U1(62)*U2(63))+HESS(4)*(U1(63)*U2(63))+HESS(5)*(U1(64)*U2(63))+HESS(6)*(U1(64)*U2(79))+HESS(56)&
              &*(U1(79)*U2(79))
  HTU(65) = 0
  HTU(66) = HESS(7)*(U1(65)*U2(79))+HESS(8)*(U1(66)*U2(79))+HESS(57)*(U1(79)*U2(79))
  HTU(67) = 0
  HTU(68) = 0
  HTU(69) = HESS(10)*(U1(68)*U2(79))+HESS(11)*(U1(69)*U2(79))+HESS(58)*(U1(79)*U2(79))
  HTU(70) = HESS(12)*(U1(70)*U2(79))+HESS(14)*(U1(72)*U2(79))+HESS(59)*(U1(79)*U2(79))
  HTU(71) = 0
  HTU(72) = HESS(13)*(U1(71)*U2(79))+HESS(15)*(U1(72)*U2(79))+HESS(60)*(U1(79)*U2(79))
  HTU(73) = HESS(9)*(U1(67)*U2(79))+HESS(16)*(U1(73)*U2(79))+HESS(61)*(U1(79)*U2(79))
  HTU(74) = HESS(18)*(U1(74)*U2(79))+HESS(19)*(U1(74)*U2(81))+HESS(31)*(U1(76)*U2(79))+HESS(32)*(U1(76)*U2(81))+HESS(62)&
              &*(U1(79)*U2(79))+HESS(63)*(U1(79)*U2(81))+HESS(79)*(U1(81)*U2(79))+HESS(80)*(U1(81)*U2(81))
  HTU(75) = HESS(21)*(U1(75)*U2(79))+HESS(22)*(U1(75)*U2(81))+HESS(33)*(U1(76)*U2(79))+HESS(34)*(U1(76)*U2(81))+HESS(64)&
              &*(U1(79)*U2(79))+HESS(65)*(U1(79)*U2(81))+HESS(81)*(U1(81)*U2(79))+HESS(82)*(U1(81)*U2(81))
  HTU(76) = HESS(17)*(U1(73)*U2(79))+HESS(35)*(U1(76)*U2(79))+HESS(66)*(U1(79)*U2(79))
  HTU(77) = HESS(36)*(U1(76)*U2(79))+HESS(37)*(U1(76)*U2(81))+HESS(42)*(U1(77)*U2(79))+HESS(43)*(U1(77)*U2(81))+HESS(67)&
              &*(U1(79)*U2(79))+HESS(68)*(U1(79)*U2(81))+HESS(83)*(U1(81)*U2(79))+HESS(84)*(U1(81)*U2(81))
  HTU(78) = HESS(25)*(U1(76)*U2(12))+HESS(28)*(U1(76)*U2(13))+HESS(38)*(U1(76)*U2(80))+HESS(46)*(U1(78)*U2(12))+HESS(47)&
              &*(U1(78)*U2(13))+HESS(48)*(U1(78)*U2(79))+HESS(49)*(U1(78)*U2(80))+HESS(69)*(U1(79)*U2(79))+HESS(73)*(U1(80)&
              &*U2(80))+HESS(85)*(U1(81)*U2(79))
  HTU(79) = HESS(1)*(U1(60)*U2(61))+HESS(2)*(U1(61)*U2(61))+HESS(6)*(U1(64)*U2(64))+HESS(7)*(U1(65)*U2(66))+HESS(8)&
              &*(U1(66)*U2(66))+HESS(9)*(U1(67)*U2(73))+HESS(10)*(U1(68)*U2(69))+HESS(11)*(U1(69)*U2(69))+HESS(12)*(U1(70)&
              &*U2(70))+HESS(13)*(U1(71)*U2(72))+HESS(14)*(U1(72)*U2(70))+HESS(15)*(U1(72)*U2(72))+HESS(16)*(U1(73)*U2(73))&
              &+HESS(17)*(U1(73)*U2(76))+HESS(18)*(U1(74)*U2(74))+HESS(20)*(U1(74)*U2(81))+HESS(21)*(U1(75)*U2(75))+HESS(23)&
              &*(U1(75)*U2(81))+HESS(31)*(U1(76)*U2(74))+HESS(33)*(U1(76)*U2(75))+HESS(35)*(U1(76)*U2(76))+HESS(36)*(U1(76)&
              &*U2(77))+HESS(39)*(U1(76)*U2(81))+HESS(42)*(U1(77)*U2(77))+HESS(44)*(U1(77)*U2(81))+HESS(48)*(U1(78)*U2(78))&
              &+HESS(55)*(U1(79)*U2(61))+HESS(56)*(U1(79)*U2(64))+HESS(57)*(U1(79)*U2(66))+HESS(58)*(U1(79)*U2(69))+HESS(59)&
              &*(U1(79)*U2(70))+HESS(60)*(U1(79)*U2(72))+HESS(61)*(U1(79)*U2(73))+HESS(62)*(U1(79)*U2(74))+HESS(64)*(U1(79)&
              &*U2(75))+HESS(66)*(U1(79)*U2(76))+HESS(67)*(U1(79)*U2(77))+HESS(69)*(U1(79)*U2(78))+HESS(70)*(U1(79)*U2(81))&
              &+HESS(79)*(U1(81)*U2(74))+HESS(81)*(U1(81)*U2(75))+HESS(83)*(U1(81)*U2(77))+HESS(85)*(U1(81)*U2(78))+HESS(86)&
              &*(U1(81)*U2(81))+HESS(91)*(U1(82)*U2(81))
  HTU(80) = HESS(38)*(U1(76)*U2(78))+HESS(40)*(U1(76)*U2(81))+HESS(41)*(U1(76)*U2(82))+HESS(49)*(U1(78)*U2(78))+HESS(71)&
              &*(U1(79)*U2(81))+HESS(72)*(U1(79)*U2(82))+HESS(73)*(U1(80)*U2(78))+HESS(74)*(U1(80)*U2(81))+HESS(75)*(U1(80)&
              &*U2(82))+HESS(87)*(U1(81)*U2(81))+HESS(92)*(U1(82)*U2(82))
  HTU(81) = HESS(19)*(U1(74)*U2(74))+HESS(20)*(U1(74)*U2(79))+HESS(22)*(U1(75)*U2(75))+HESS(23)*(U1(75)*U2(79))+HESS(26)&
              &*(U1(76)*U2(12))+HESS(29)*(U1(76)*U2(13))+HESS(32)*(U1(76)*U2(74))+HESS(34)*(U1(76)*U2(75))+HESS(37)*(U1(76)&
              &*U2(77))+HESS(39)*(U1(76)*U2(79))+HESS(40)*(U1(76)*U2(80))+HESS(43)*(U1(77)*U2(77))+HESS(44)*(U1(77)*U2(79))&
              &+HESS(51)*(U1(79)*U2(12))+HESS(53)*(U1(79)*U2(13))+HESS(63)*(U1(79)*U2(74))+HESS(65)*(U1(79)*U2(75))+HESS(68)&
              &*(U1(79)*U2(77))+HESS(70)*(U1(79)*U2(79))+HESS(71)*(U1(79)*U2(80))+HESS(74)*(U1(80)*U2(80))+HESS(77)*(U1(81)&
              &*U2(12))+HESS(78)*(U1(81)*U2(13))+HESS(80)*(U1(81)*U2(74))+HESS(82)*(U1(81)*U2(75))+HESS(84)*(U1(81)*U2(77))&
              &+HESS(86)*(U1(81)*U2(79))+HESS(87)*(U1(81)*U2(80))+HESS(91)*(U1(82)*U2(79))
  HTU(82) = HESS(27)*(U1(76)*U2(12))+HESS(30)*(U1(76)*U2(13))+HESS(41)*(U1(76)*U2(80))+HESS(52)*(U1(79)*U2(12))+HESS(54)&
              &*(U1(79)*U2(13))+HESS(72)*(U1(79)*U2(80))+HESS(75)*(U1(80)*U2(80))+HESS(89)*(U1(82)*U2(12))+HESS(90)*(U1(82)&
              &*U2(13))+HESS(92)*(U1(82)*U2(80))
      
END SUBROUTINE HessTR_Vec

! End of HessTR_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Hess_Vec - Hessian times user vectors
!   Arguments :
!      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
!      U1        - User vector
!      U2        - User vector
!      HU        - Hessian times user vectors: (Hess x U2) * U1 = [d (Jac*U1)/d Var] * U2
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Hess_Vec ( HESS, U1, U2, HU )

! HESS - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
  REAL(kind=dp) :: HESS(NHESS)
! U1 - User vector
  REAL(kind=dp) :: U1(NVAR)
! U2 - User vector
  REAL(kind=dp) :: U2(NVAR)
! HU - Hessian times user vectors: (Hess x U2) * U1 = [d (Jac*U1)/d Var] * U2
  REAL(kind=dp) :: HU(NVAR)

! Compute the vector HU =(Hess x U2) * U1 = d (Jac*U1)/d Var * U2
  HU(1) = 0
  HU(2) = 0
  HU(3) = 0
  HU(4) = 0
  HU(5) = 0
  HU(6) = 0
  HU(7) = 0
  HU(8) = 0
  HU(9) = 0
  HU(10) = 0
  HU(11) = 0
  HU(12) = 0
  HU(13) = 0
  HU(14) = 0
  HU(15) = 0
  HU(16) = 0
  HU(17) = 0
  HU(18) = 0
  HU(19) = 0
  HU(20) = 0
  HU(21) = 0
  HU(22) = 0
  HU(23) = 0
  HU(24) = 0
  HU(25) = 0
  HU(26) = 0
  HU(27) = 0
  HU(28) = 0
  HU(29) = 0
  HU(30) = 0
  HU(31) = 0
  HU(32) = 0
  HU(33) = 0
  HU(34) = 0
  HU(35) = 0
  HU(36) = 0
  HU(37) = 0
  HU(38) = 0
  HU(39) = 0
  HU(40) = 0
  HU(41) = 0
  HU(42) = 0
  HU(43) = 0
  HU(44) = 0
  HU(45) = 0
  HU(46) = 0
  HU(47) = 0
  HU(48) = 0
  HU(49) = 0
  HU(50) = 0
  HU(51) = 0
  HU(52) = 0
  HU(53) = 0
  HU(54) = 0
  HU(55) = 0
  HU(56) = 0
  HU(57) = 0
  HU(58) = 0
  HU(59) = 0
  HU(60) = HESS(1)*(U1(61)*U2(79))+HESS(1)*(U1(79)*U2(61))
  HU(61) = HESS(2)*(U1(61)*U2(79))+HESS(2)*(U1(79)*U2(61))
  HU(62) = HESS(3)*(U1(63)*U2(64))+HESS(3)*(U1(64)*U2(63))
  HU(63) = HESS(4)*(U1(63)*U2(64))+HESS(4)*(U1(64)*U2(63))
  HU(64) = HESS(5)*(U1(63)*U2(64))+HESS(5)*(U1(64)*U2(63))+HESS(6)*(U1(64)*U2(79))+HESS(6)*(U1(79)*U2(64))
  HU(65) = HESS(7)*(U1(66)*U2(79))+HESS(7)*(U1(79)*U2(66))
  HU(66) = HESS(8)*(U1(66)*U2(79))+HESS(8)*(U1(79)*U2(66))
  HU(67) = HESS(9)*(U1(73)*U2(79))+HESS(9)*(U1(79)*U2(73))
  HU(68) = HESS(10)*(U1(69)*U2(79))+HESS(10)*(U1(79)*U2(69))
  HU(69) = HESS(11)*(U1(69)*U2(79))+HESS(11)*(U1(79)*U2(69))
  HU(70) = HESS(12)*(U1(70)*U2(79))+HESS(12)*(U1(79)*U2(70))
  HU(71) = HESS(13)*(U1(72)*U2(79))+HESS(13)*(U1(79)*U2(72))
  HU(72) = HESS(14)*(U1(70)*U2(79))+HESS(14)*(U1(79)*U2(70))+HESS(15)*(U1(72)*U2(79))+HESS(15)*(U1(79)*U2(72))
  HU(73) = HESS(16)*(U1(73)*U2(79))+HESS(16)*(U1(79)*U2(73))+HESS(17)*(U1(76)*U2(79))+HESS(17)*(U1(79)*U2(76))
  HU(74) = HESS(18)*(U1(74)*U2(79))+HESS(18)*(U1(79)*U2(74))+HESS(19)*(U1(74)*U2(81))+HESS(19)*(U1(81)*U2(74))+HESS(20)&
             &*(U1(79)*U2(81))+HESS(20)*(U1(81)*U2(79))
  HU(75) = HESS(21)*(U1(75)*U2(79))+HESS(21)*(U1(79)*U2(75))+HESS(22)*(U1(75)*U2(81))+HESS(22)*(U1(81)*U2(75))+HESS(23)&
             &*(U1(79)*U2(81))+HESS(23)*(U1(81)*U2(79))
  HU(76) = HESS(24)*(U1(12)*U2(13))+HESS(24)*(U1(13)*U2(12))+HESS(25)*(U1(12)*U2(78))+HESS(25)*(U1(78)*U2(12))+HESS(26)&
             &*(U1(12)*U2(81))+HESS(26)*(U1(81)*U2(12))+HESS(27)*(U1(12)*U2(82))+HESS(27)*(U1(82)*U2(12))+HESS(28)*(U1(13)&
             &*U2(78))+HESS(28)*(U1(78)*U2(13))+HESS(29)*(U1(13)*U2(81))+HESS(29)*(U1(81)*U2(13))+HESS(30)*(U1(13)*U2(82))&
             &+HESS(30)*(U1(82)*U2(13))+HESS(31)*(U1(74)*U2(79))+HESS(31)*(U1(79)*U2(74))+HESS(32)*(U1(74)*U2(81))+HESS(32)&
             &*(U1(81)*U2(74))+HESS(33)*(U1(75)*U2(79))+HESS(33)*(U1(79)*U2(75))+HESS(34)*(U1(75)*U2(81))+HESS(34)*(U1(81)&
             &*U2(75))+HESS(35)*(U1(76)*U2(79))+HESS(35)*(U1(79)*U2(76))+HESS(36)*(U1(77)*U2(79))+HESS(36)*(U1(79)*U2(77))&
             &+HESS(37)*(U1(77)*U2(81))+HESS(37)*(U1(81)*U2(77))+HESS(38)*(U1(78)*U2(80))+HESS(38)*(U1(80)*U2(78))+HESS(39)&
             &*(U1(79)*U2(81))+HESS(39)*(U1(81)*U2(79))+HESS(40)*(U1(80)*U2(81))+HESS(40)*(U1(81)*U2(80))+HESS(41)*(U1(80)&
             &*U2(82))+HESS(41)*(U1(82)*U2(80))
  HU(77) = HESS(42)*(U1(77)*U2(79))+HESS(42)*(U1(79)*U2(77))+HESS(43)*(U1(77)*U2(81))+HESS(43)*(U1(81)*U2(77))+HESS(44)&
             &*(U1(79)*U2(81))+HESS(44)*(U1(81)*U2(79))
  HU(78) = HESS(45)*(U1(12)*U2(13))+HESS(45)*(U1(13)*U2(12))+HESS(46)*(U1(12)*U2(78))+HESS(46)*(U1(78)*U2(12))+HESS(47)&
             &*(U1(13)*U2(78))+HESS(47)*(U1(78)*U2(13))+HESS(48)*(U1(78)*U2(79))+HESS(48)*(U1(79)*U2(78))+HESS(49)*(U1(78)&
             &*U2(80))+HESS(49)*(U1(80)*U2(78))
  HU(79) = HESS(50)*(U1(12)*U2(13))+HESS(50)*(U1(13)*U2(12))+HESS(51)*(U1(12)*U2(81))+HESS(51)*(U1(81)*U2(12))+HESS(52)&
             &*(U1(12)*U2(82))+HESS(52)*(U1(82)*U2(12))+HESS(53)*(U1(13)*U2(81))+HESS(53)*(U1(81)*U2(13))+HESS(54)*(U1(13)&
             &*U2(82))+HESS(54)*(U1(82)*U2(13))+HESS(55)*(U1(61)*U2(79))+HESS(55)*(U1(79)*U2(61))+HESS(56)*(U1(64)*U2(79))&
             &+HESS(56)*(U1(79)*U2(64))+HESS(57)*(U1(66)*U2(79))+HESS(57)*(U1(79)*U2(66))+HESS(58)*(U1(69)*U2(79))+HESS(58)&
             &*(U1(79)*U2(69))+HESS(59)*(U1(70)*U2(79))+HESS(59)*(U1(79)*U2(70))+HESS(60)*(U1(72)*U2(79))+HESS(60)*(U1(79)&
             &*U2(72))+HESS(61)*(U1(73)*U2(79))+HESS(61)*(U1(79)*U2(73))+HESS(62)*(U1(74)*U2(79))+HESS(62)*(U1(79)*U2(74))&
             &+HESS(63)*(U1(74)*U2(81))+HESS(63)*(U1(81)*U2(74))+HESS(64)*(U1(75)*U2(79))+HESS(64)*(U1(79)*U2(75))+HESS(65)&
             &*(U1(75)*U2(81))+HESS(65)*(U1(81)*U2(75))+HESS(66)*(U1(76)*U2(79))+HESS(66)*(U1(79)*U2(76))+HESS(67)*(U1(77)&
             &*U2(79))+HESS(67)*(U1(79)*U2(77))+HESS(68)*(U1(77)*U2(81))+HESS(68)*(U1(81)*U2(77))+HESS(69)*(U1(78)*U2(79))&
             &+HESS(69)*(U1(79)*U2(78))+HESS(70)*(U1(79)*U2(81))+HESS(70)*(U1(81)*U2(79))+HESS(71)*(U1(80)*U2(81))+HESS(71)&
             &*(U1(81)*U2(80))+HESS(72)*(U1(80)*U2(82))+HESS(72)*(U1(82)*U2(80))
  HU(80) = HESS(73)*(U1(78)*U2(80))+HESS(73)*(U1(80)*U2(78))+HESS(74)*(U1(80)*U2(81))+HESS(74)*(U1(81)*U2(80))+HESS(75)&
             &*(U1(80)*U2(82))+HESS(75)*(U1(82)*U2(80))
  HU(81) = HESS(76)*(U1(12)*U2(13))+HESS(76)*(U1(13)*U2(12))+HESS(77)*(U1(12)*U2(81))+HESS(77)*(U1(81)*U2(12))+HESS(78)&
             &*(U1(13)*U2(81))+HESS(78)*(U1(81)*U2(13))+HESS(79)*(U1(74)*U2(79))+HESS(79)*(U1(79)*U2(74))+HESS(80)*(U1(74)&
             &*U2(81))+HESS(80)*(U1(81)*U2(74))+HESS(81)*(U1(75)*U2(79))+HESS(81)*(U1(79)*U2(75))+HESS(82)*(U1(75)*U2(81))&
             &+HESS(82)*(U1(81)*U2(75))+HESS(83)*(U1(77)*U2(79))+HESS(83)*(U1(79)*U2(77))+HESS(84)*(U1(77)*U2(81))+HESS(84)&
             &*(U1(81)*U2(77))+HESS(85)*(U1(78)*U2(79))+HESS(85)*(U1(79)*U2(78))+HESS(86)*(U1(79)*U2(81))+HESS(86)*(U1(81)&
             &*U2(79))+HESS(87)*(U1(80)*U2(81))+HESS(87)*(U1(81)*U2(80))
  HU(82) = HESS(88)*(U1(12)*U2(13))+HESS(88)*(U1(13)*U2(12))+HESS(89)*(U1(12)*U2(82))+HESS(89)*(U1(82)*U2(12))+HESS(90)&
             &*(U1(13)*U2(82))+HESS(90)*(U1(82)*U2(13))+HESS(91)*(U1(79)*U2(81))+HESS(91)*(U1(81)*U2(79))+HESS(92)*(U1(80)&
             &*U2(82))+HESS(92)*(U1(82)*U2(80))
      
END SUBROUTINE Hess_Vec

! End of Hess_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE aqchem_Hessian

