! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : aqchem_Rates.f90
! Time                 : Thu Jul 30 15:45:59 2015
! Working directory    : /home/slz/buf/dev/cmaq-adj/ad/aqchem-kpp/src-aero5-adj
! Equation file        : aqchem.kpp
! Output root filename : aqchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE aqchem_Rates

  USE aqchem_Parameters
  USE aqchem_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions



REAL( kind=dp )FUNCTION KMTF ( ACC, DG, MW )

 implicit none
 
 REAL( kind=dp ) ACC  ! accommodation coefficient     ! unitless
 REAL( kind=dp ) DG  ! Gas molecular diffusion coef !m2/s
 REAL( kind=dp ) MW  ! molecular weight
 REAL( kind=dp ) KMT, RHO1, RAD, R, PI, V
 
 RHO1 = 1.D0 !g/mL - density of H2O
 RAD = DDIAM * 0.5D0 ! m
 R = 8.3145d0
 PI = 3.1415926536
 KMT = ( RAD*RAD ) / ( 3.D0 * DG )
 V = SQRT( 8.D0 * R * TEMP_KPP * 1000.d0 / PI / MW ) !V = ( 8.D0 * R * TEMP_KPP * 1000.d0 / PI / MW )**0.5  ! m/s
 KMT = KMT + ( 4 * RAD / ( 3 * V * ACC ) )
 KMT = 1.D0 / KMT  ! from Schwartz, 1986
 KMTF = KMT * LWC_KPP / 1000.D0 ! implied division by RHO1 (=1)
 
 RETURN
 
END FUNCTION KMTF

REAL( kind=dp )FUNCTION KMTB ( HL, DH, ACC, DG, MW )

 implicit none
 
 REAL( kind=dp ) HL, DH
 REAL( kind=dp ) ACC  ! accommodation coefficient
 REAL( kind=dp ) DG  ! Gas molecular diffusion coef
 REAL( kind=dp ) MW  ! molecular weight
 REAL( kind=dp ) HLCONST, RHO1, RAD, R, PI, KMT, V, R2
 
 RAD = DDIAM * 0.5D0
 R = 8.3145d0 ! J / mol-K
 R2 = 0.08206D0 ! L-atm / mol-K  (= R/101325)
 PI = 3.1415926536
 KMT = ( RAD * RAD ) / ( 3.D0 * DG )
 V = SQRT( 8.D0 * R * TEMP_KPP * 1000.d0 / PI / MW ) ! ( 8.D0 * R * TEMP_KPP * 1000.d0 / PI / MW )**0.5  ! m/s
 KMT = KMT + ( 4 * RAD / ( 3 * V * ACC ) )
 KMT = 1.D0 / KMT  ! from Schwartz, 1986
 HLCONST = HL * EXP( DH * ( DELINVT ) )
 KMTB = KMT / ( R2 * TEMP_KPP * HLCONST )
 
 RETURN
 
END FUNCTION KMTB

REAL( kind=dp )FUNCTION DISF ( Keq, DH, kb, G1 )

          implicit none
       
          REAL( kind=dp ) DH, Keq, kb
	  INTEGER  G1
         
           DISF = kb * ( Keq * EXP( DH * DELINVT ) )
	   IF( G1 .eq. 1 ) DISF = DISF * ( GM1 ) 
        
        RETURN
     
END FUNCTION DISF 
REAL( kind=dp )FUNCTION DISB ( kb, G1 )

          implicit none
       
          REAL( kind=dp ) kb 
	  INTEGER G1
	  
	  DISB = kb
          IF( G1 .eq. 1 ) DISB   = DISB * ( GM1 ) * ( GM2 )
	  IF( G1 .eq. 2 ) DISB   = DISB * ( GM1 * GM1 )
          DISB = DISB * PHI2     
             
        RETURN
     
END FUNCTION DISB


REAL( kind=dp )FUNCTION ORG ( korg )

          implicit none
       
            REAL( kind=dp ) korg
         
            ORG = korg
            ORG = ORG * PHI2
         
        RETURN
     
END FUNCTION ORG

REAL( kind=dp )FUNCTION KRXN ( kr, DH, RTYPE, QY, METAL )

          implicit none
       
          REAL( kind=dp ) kr, DH
          REAL( kind=dp ) Q, q1, COTHq, SVIinh
          INTEGER QY, RTYPE, METAL
	  
	  SVIinh = 1.d0 + 75.d0 * ((var(ind_L_H2SO4) + var(ind_L_HSO4MIN) + &
	   var(ind_L_SO4MIN2)) * PHI2)**0.67d0 !SO4 inhibition of metal catalysis

          KRXN = kr * EXP( DH * DELINVT)
          if (RTYPE .eq. 1 ) then   ! so2 - h2o2 OXIDATION
                  KRXN = (KRXN / (1.0D0 + 13.D0*var(ind_L_HPLUS) * PHI2)) * PHI2
!          elseif (RTYPE .eq. 2 ) then   ! so2 - PAA OXIDATION
!                  KRXN = KRXN * (var(ind_L_HPLUS) * PHI2) + 7.00D2  
          elseif (RTYPE .eq. 3 ) then   ! so2 - Fe3/Mn2 synergism and MHP and PAA reaction
                  KRXN = KRXN * PHI2          
          endif
	  
	  IF (METAL .gt. 0) KRXN = KRXN / SVIinh

! Ionic strength impact on SIV-O3 reaction rate       
!       IF (QY .gt. 0) THEN
!       KRXN = KRXN * (1.d0 + 2.5 * STION)
!       ENDIF       
!
! Aqueous diffusion limitation
!
!
	  q1 = 0.d0
	  Q = 1.d0
       
       var(ind_L_SO2)=max(var(ind_L_SO2),0.)  !slz
       var(ind_L_HSO3MIN)=max(var(ind_L_HSO3MIN),0.)  !slz
       var(ind_L_SO3MIN2)=max(var(ind_L_SO3MIN2),0.)  !slz

       IF(QY .eq. 1) q1 = DDIAM/2.d0 * ( KRXN * var(ind_L_SO2) * PHI2 / DAQ )**0.5d0
       IF(QY .eq. 2) q1 = DDIAM/2.d0 * ( KRXN * var(ind_L_HSO3MIN) * PHI2 / DAQ )**0.5d0
       IF(QY .eq. 3) q1 = DDIAM/2.d0 * ( KRXN * var(ind_L_SO3MIN2) * PHI2 / DAQ )**0.5d0

       IF(q1 .gt. 1.d-3) THEN
       IF(q1 .le. 100.d0) THEN
          COTHq = (EXP(2*q1)+1) / (EXP(2*q1)-1)
       Q = 3 * (COTHq/q1 - 1.d0/(q1*q1))
       IF(Q .gt. 1.d0) Q = 1.d0
       ELSE
       Q = 3.d0/q1
       ENDIF
       ELSE
       Q = 1.d0
       ENDIF
       KRXN = KRXN * Q       


!       
!       IF(QY .eq. 1) q1 = DDIAM/2.d0 * ( KRXN * var(ind_L_SO2) * PHI2 / DAQ )**0.5d0
!       IF(QY .eq. 2) q1 = DDIAM/2.d0 * ( KRXN * var(ind_L_HSO3MIN) * PHI2 / DAQ )**0.5d0
!       IF(QY .eq. 3) q1 = DDIAM/2.d0 * ( KRXN * var(ind_L_SO3MIN2) * PHI2 / DAQ )**0.5d0
!
!       IF(q1 .gt. 1.d-3) THEN
!          COTHq = (EXP(2*q1)+1) / (EXP(2*q1)-1)
!       Q = 3 * (COTHq/q1 - 1.d0/(q1**2))
!       IF(Q .gt. 1.d0) Q = 1.d0
!       ELSE
!       Q = 1.d0
!       ENDIF
!       KRXN = KRXN * Q

       KRXN = KRXN * PHI2
       
        RETURN
     
END FUNCTION KRXN


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE aqchem_Parameters
      !USE aqchem_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


         STION = 0.5D0  &
               * (var(ind_L_HPLUS) + var(ind_L_NH4PLUS) + var(ind_L_OHMIN)  &
               + var(ind_L_HCO3MIN) &
               + var(ind_L_HSO3MIN) + var(ind_L_HCOOMIN) + var(ind_L_NO3MIN) &
               + var(ind_L_HSO4MIN)  &
               + var( ind_L_NAPLUS) + var(ind_L_KPLUS) + var( ind_L_CLMIN ) &
               + 3*var(ind_L_FEPLUS3) + 2*var(ind_L_MNPLUS2) &
               + 4.0D0 * ( var(ind_L_SO4MIN2)  + var(ind_L_CO3MIN2) &
               +  var( ind_L_SO3MIN2) + var(ind_L_MNPLUS2) + var( ind_L_CAPLUS2 ) &
               +  var( ind_L_MGPLUS2 ) ) &
               + 9.0D0 * var(ind_L_FEPLUS3) ) * PHI2 !includes anions for Fe3+ and Mn2+
         
           GM1LOG = -0.509D0 * ( SQRT( STION ) &
               / ( 1.0D0 + SQRT( STION ) ) - 0.2D0 * STION )
           GM2LOG = GM1LOG * 4.0D0
           GM1    = 10.0D0**GM1LOG
           GM2    = MAX( 10.0D0**GM2LOG, 1.0D-30 )   


! End INLINED RCONST

  RCONST(1) = ((KMTF(0.11D0,1.28D-5,64.064D0)))
  RCONST(2) = ((KMTF(0.0868D0,1.32D-5,63.013D0)))
  RCONST(3) = ((KMTF(0.00015D0,1.55D-5,44.01D0)))
  RCONST(4) = ((KMTF(0.091D0,2.3D-5,17.031D0)))
  RCONST(5) = ((KMTF(0.1532D0,1.46D-5,34.015D0)))
  RCONST(6) = ((KMTF(0.1D0,1.48D-5,47.998D0)))
  RCONST(7) = ((KMTF(0.0229D0,1.53D-5,46.025D0)))
  RCONST(8) = ((KMTF(0.006758D0,1.31D-5,48.04D0)))
  RCONST(9) = ((KMTF(0.019D0,1.02D-5,76.05D0)))
  RCONST(10) = ((KMTF(0.1158D0,1.89D-5,36.461D0)))
  RCONST(11) = ((KMTF(0.023D0,1.15D-5,58.04D0)))
  RCONST(12) = ((KMTF(0.023D0,1.15D-5,72.06D0)))
  RCONST(13) = ((KMTB(1.4D+00,2.9D+03,0.11D0,1.28D-5,64.064D0)))
  RCONST(14) = ((KMTB(2.1D+05,8.7D+03,0.0868D0,1.32D-5,63.013D0)))
  RCONST(15) = ((KMTB(3.6D-02,2.2D+03,0.00015D0,1.55D-5,44.01D0)))
  RCONST(16) = ((KMTB(6.1D+01,4.2D+03,0.091D0,2.3D-5,17.031D0)))
  RCONST(17) = ((KMTB(8.3D+04,7.4D+03,0.1532D0,1.46D-5,34.015D0)))
  RCONST(18) = ((KMTB(1.14D-02,2.3D+03,0.1D0,1.48D-5,47.998D0)))
  RCONST(19) = ((KMTB(8.9D+03,6.1D+03,0.0229D0,1.53D-5,46.025D0)))
  RCONST(20) = ((KMTB(3.1D+02,5.2D+03,0.006758D0,1.31D-5,48.04D0)))
  RCONST(21) = ((KMTB(8.4D+02,5.3D+03,0.019D0,1.02D-5,76.05D0)))
  RCONST(22) = ((KMTB(1.9D+01,6.0D+02,0.1158D0,1.89D-5,36.461D0)))
  RCONST(23) = ((KMTB(3.6D+05,0.0D+00,0.023D0,1.15D-5,58.04D0)))
  RCONST(24) = ((KMTB(MGLYH,0.0D+0,0.023D0,1.15D-5,72.06D0)))
  RCONST(25) = (ALFA3_KPP)
  RCONST(26) = (ALFA3_KPP)
  RCONST(27) = (ALFA3_KPP)
  RCONST(28) = (ALFA3_KPP)
  RCONST(29) = (ALFA3_KPP)
  RCONST(30) = (ALFA3_KPP)
  RCONST(31) = (ALFA3_KPP)
  RCONST(32) = (ALFA3_KPP)
  RCONST(33) = ((DISF(1.39D-02,1.87D+03,2.D8,0)))
  RCONST(34) = ((DISF(6.72D-08,3.55D+02,5.D10,1)))
  RCONST(35) = ((DISF(1.7D+01,0.D0,5.D10,0)))
  RCONST(36) = ((DISF(4.30D-07,-9.95D+02,6.4D4,0)))
  RCONST(37) = ((DISF(4.68D-11,-1.785D+03,5.D10,1)))
  RCONST(38) = ((DISF(1.77D-5,-7.10D+02,3.4D10,0)))
  RCONST(39) = ((DISF(1.80D-4,-2.00D+01,5.D10,0)))
  RCONST(40) = ((DISF(1.74D+06,6.89D+03,5.D10,0)))
  RCONST(41) = ((DISF(1.80D-16,-6.955D+03,1.4D11,0)))
  RCONST(42) = ((DISF(1000.D0,0.D0,5.D10,0)))
  RCONST(43) = ((DISF(1.02D-2,2.445D+03,1.D11,1)))
  RCONST(44) = ((DISB(2.D8,2)))
  RCONST(45) = ((DISB(5.D10,1)))
  RCONST(46) = ((DISB(5.D10,2)))
  RCONST(47) = ((DISB(6.4D4,2)))
  RCONST(48) = ((DISB(5.D10,1)))
  RCONST(49) = ((DISB(3.4D10,2)))
  RCONST(50) = ((DISB(5.D10,2)))
  RCONST(51) = ((DISB(5.D10,2)))
  RCONST(52) = ((DISB(1.4D11,2)))
  RCONST(53) = ((DISB(5.D10,2)))
  RCONST(54) = ((DISB(1.D11,1)))
  RCONST(55) = ((ORG(3.0D10)))
  RCONST(56) = ((ORG(3.0D10)))
  RCONST(57) = ((KRXN(7.45D+7,-4756.08D0,1,0,0)))
  RCONST(58) = ((KRXN(2.4D+4,0.D0,0,1,0)))
  RCONST(59) = ((KRXN(3.7D+5,-5530.88D0,0,2,0)))
  RCONST(60) = ((KRXN(1.5D+9,-5280.56D0,0,3,0)))
  RCONST(61) = ((KRXN(750.D0,0.D0,0,0,1)))
  RCONST(62) = ((KRXN(750.D0,0.D0,0,0,1)))
  RCONST(63) = ((KRXN(750.D0,0.D0,0,0,1)))
  RCONST(64) = ((KRXN(2600.D0,0.D0,0,0,1)))
  RCONST(65) = ((KRXN(2600.D0,0.D0,0,0,1)))
  RCONST(66) = ((KRXN(2600.D0,0.D0,0,0,1)))
  RCONST(67) = ((KRXN(1.0D10,0.D0,3,0,1)))
  RCONST(68) = ((KRXN(1.0D10,0.D0,3,0,1)))
  RCONST(69) = ((KRXN(1.0D10,0.D0,3,0,1)))
  RCONST(70) = ((KRXN(1.90D+07,-3799.5D0,3,0,0)))
  RCONST(71) = ((KRXN(3.60D+07,-3999.2D0,3,0,0)))
  RCONST(72) = ((KRXN(7.0D+02,0D0,0,0,0)))
  RCONST(73) = (WETFAC_KPP)
  RCONST(74) = (WETFAC_KPP)
  RCONST(75) = (WETFAC_KPP)
  RCONST(76) = (WETFAC_KPP)
  RCONST(77) = (WETFAC_KPP)
  RCONST(78) = (WETFAC_KPP)
  RCONST(79) = (WETFAC_KPP)
  RCONST(80) = (WETFAC_KPP)
  RCONST(81) = (WETFAC_KPP)
  RCONST(82) = (WETFAC_KPP)
  RCONST(83) = (WETFAC_KPP)
  RCONST(84) = (WETFAC_KPP)
  RCONST(85) = (WETFAC_KPP)
  RCONST(86) = (WETFAC_KPP)
  RCONST(87) = (WETFAC_KPP)
  RCONST(88) = (WETFAC_KPP)
  RCONST(89) = (WETFAC_KPP)
  RCONST(90) = (WETFAC_KPP)
  RCONST(91) = (WETFAC_KPP)
  RCONST(92) = (WETFAC_KPP)
  RCONST(93) = (WETFAC_KPP)
  RCONST(94) = (WETFAC_KPP)
  RCONST(95) = (WETFAC_KPP)
  RCONST(96) = (WETFAC_KPP)
  RCONST(97) = (WETFAC_KPP)
  RCONST(98) = (WETFAC_KPP)
  RCONST(99) = (WETFAC_KPP)
  RCONST(100) = (WETFAC_KPP)
  RCONST(101) = (WETFAC_KPP)
  RCONST(102) = (WETFAC_KPP)
  RCONST(103) = (WETFAC_KPP)
  RCONST(104) = (WETFAC_KPP)
  RCONST(105) = (WETFAC_KPP)
  RCONST(106) = (WETFAC_KPP)
  RCONST(107) = (WETFAC_KPP)
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE aqchem_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE aqchem_Rates

